import { User, Patient, Appointment, Invoice, DashboardStats, TodaySchedule, ToothRecord } from '@/types';

export const MOCK_USERS: Record<string, User> = {
  'admin@meridian.dental': {
    id: 'usr-admin-01',
    email: 'admin@meridian.dental',
    full_name: 'Dr. Arthur Meridian',
    role: 'admin',
    clinic_id: 'cln-01',
    phone: '+91-9876543210',
    specialization: 'Chief Dental Officer & Surgeon',
    is_active: true,
  },
  'dentist@meridian.dental': {
    id: 'usr-dentist-01',
    email: 'dentist@meridian.dental',
    full_name: 'Dr. Sarah Jenkins',
    role: 'dentist',
    clinic_id: 'cln-01',
    phone: '+91-9876543211',
    specialization: 'Orthodontics & Cosmetic Dentistry',
    is_active: true,
  },
  'receptionist@meridian.dental': {
    id: 'usr-recep-01',
    email: 'receptionist@meridian.dental',
    full_name: 'Emily Watson',
    role: 'receptionist',
    clinic_id: 'cln-01',
    phone: '+91-9876543212',
    is_active: true,
  },
  'accountant@meridian.dental': {
    id: 'usr-acc-01',
    email: 'accountant@meridian.dental',
    full_name: 'Michael Chang',
    role: 'accountant',
    clinic_id: 'cln-01',
    phone: '+91-9876543213',
    is_active: true,
  },
};

export const MOCK_STATS: DashboardStats = {
  total_patients: 1248,
  todays_appointments: 14,
  completed_appointments: 8,
  pending_appointments: 5,
  cancelled_appointments: 1,
  todays_revenue: 48500,
  outstanding_amount: 18200,
  new_patients_this_month: 38,
};

export const MOCK_SCHEDULE: TodaySchedule[] = [
  {
    appointment_id: 'apt-01',
    patient_name: 'Sophia Reynolds',
    time: '09:00 AM',
    type: 'Root Canal Treatment',
    duration: 60,
    status: 'completed',
  },
  {
    appointment_id: 'apt-02',
    patient_name: 'Marcus Vance',
    time: '10:30 AM',
    type: 'Teeth Whitening',
    duration: 45,
    status: 'completed',
  },
  {
    appointment_id: 'apt-03',
    patient_name: 'Aria Sharma',
    time: '11:45 AM',
    type: 'Orthodontic Checkup',
    duration: 30,
    status: 'in_progress',
  },
  {
    appointment_id: 'apt-04',
    patient_name: 'David Miller',
    time: '02:00 PM',
    type: 'Crown Placement',
    duration: 60,
    status: 'scheduled',
  },
  {
    appointment_id: 'apt-05',
    patient_name: 'Emma Watson',
    time: '03:30 PM',
    type: 'Dental Cleaning',
    duration: 30,
    status: 'scheduled',
  },
];

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'pat-01',
    patient_id_display: 'PAT-1001',
    full_name: 'Sophia Reynolds',
    date_of_birth: '1992-05-14',
    gender: 'Female',
    phone: '+91 98451 23456',
    email: 'sophia.reynolds@example.com',
    address: '42 Greenwood Avenue, Chennai',
    blood_group: 'O+',
    allergies: 'Penicillin',
    medical_history: 'Mild Asthma',
    status: 'active',
    created_at: '2025-01-15T10:00:00Z',
    updated_at: '2025-09-10T14:30:00Z',
  },
  {
    id: 'pat-02',
    patient_id_display: 'PAT-1002',
    full_name: 'Marcus Vance',
    date_of_birth: '1988-11-23',
    gender: 'Male',
    phone: '+91 97890 65432',
    email: 'marcus.vance@example.com',
    address: '18 Lakeview Road, Bangalore',
    blood_group: 'A+',
    allergies: 'None',
    medical_history: 'None',
    status: 'active',
    created_at: '2025-02-10T09:20:00Z',
    updated_at: '2025-09-08T11:15:00Z',
  },
  {
    id: 'pat-03',
    patient_id_display: 'PAT-1003',
    full_name: 'Aria Sharma',
    date_of_birth: '2001-03-08',
    gender: 'Female',
    phone: '+91 98765 43210',
    email: 'aria.sharma@example.com',
    address: '7 Residency Road, Hyderabad',
    blood_group: 'B+',
    allergies: 'Latex',
    medical_history: 'Wearing braces',
    status: 'active',
    created_at: '2025-03-01T15:45:00Z',
    updated_at: '2025-09-12T16:00:00Z',
  },
  {
    id: 'pat-04',
    patient_id_display: 'PAT-1004',
    full_name: 'David Miller',
    date_of_birth: '1975-07-19',
    gender: 'Male',
    phone: '+91 94440 98765',
    email: 'david.miller@example.com',
    address: '105 Palm Grove, Chennai',
    blood_group: 'AB+',
    allergies: 'None',
    medical_history: 'Hypertension',
    status: 'active',
    created_at: '2025-03-20T11:00:00Z',
    updated_at: '2025-09-11T10:20:00Z',
  },
  {
    id: 'pat-05',
    patient_id_display: 'PAT-1005',
    full_name: 'Emma Watson',
    date_of_birth: '1995-09-30',
    gender: 'Female',
    phone: '+91 91234 56789',
    email: 'emma.w@example.com',
    address: '22 Marine Drive, Mumbai',
    blood_group: 'O-',
    allergies: 'None',
    medical_history: 'None',
    status: 'active',
    created_at: '2025-04-05T14:10:00Z',
    updated_at: '2025-09-09T18:00:00Z',
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-01',
    patient_id: 'pat-01',
    dentist_id: 'usr-dentist-01',
    patient_name: 'Sophia Reynolds',
    dentist_name: 'Dr. Sarah Jenkins',
    date: new Date().toISOString().split('T')[0],
    start_time: '09:00',
    end_time: '10:00',
    duration_minutes: 60,
    appointment_type: 'Root Canal',
    status: 'completed',
    notes: 'Tooth #14 root canal completed without complications.',
    created_at: '2025-09-01T08:00:00Z',
  },
  {
    id: 'apt-02',
    patient_id: 'pat-02',
    dentist_id: 'usr-admin-01',
    patient_name: 'Marcus Vance',
    dentist_name: 'Dr. Arthur Meridian',
    date: new Date().toISOString().split('T')[0],
    start_time: '10:30',
    end_time: '11:15',
    duration_minutes: 45,
    appointment_type: 'Whitening',
    status: 'completed',
    notes: 'Laser whitening shade improved by 4 tones.',
    created_at: '2025-09-02T09:00:00Z',
  },
  {
    id: 'apt-03',
    patient_id: 'pat-03',
    dentist_id: 'usr-dentist-01',
    patient_name: 'Aria Sharma',
    dentist_name: 'Dr. Sarah Jenkins',
    date: new Date().toISOString().split('T')[0],
    start_time: '11:45',
    end_time: '12:15',
    duration_minutes: 30,
    appointment_type: 'Orthodontics',
    status: 'in_progress',
    notes: 'Wire tightening for upper arch.',
    created_at: '2025-09-03T10:00:00Z',
  },
  {
    id: 'apt-04',
    patient_id: 'pat-04',
    dentist_id: 'usr-admin-01',
    patient_name: 'David Miller',
    dentist_name: 'Dr. Arthur Meridian',
    date: new Date().toISOString().split('T')[0],
    start_time: '14:00',
    end_time: '15:00',
    duration_minutes: 60,
    appointment_type: 'Crown',
    status: 'scheduled',
    notes: 'Zirconia crown fitting for tooth #19.',
    created_at: '2025-09-04T11:00:00Z',
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-01',
    patient_id: 'pat-01',
    patient_name: 'Sophia Reynolds',
    invoice_number: 'INV-2025-001',
    invoice_date: '2025-09-10',
    due_date: '2025-09-20',
    subtotal: 12000,
    discount_amount: 1000,
    tax_amount: 1980,
    total_amount: 12980,
    amount_paid: 12980,
    balance: 0,
    status: 'paid',
    items: [
      { id: 'itm-1', description: 'Molar Root Canal Treatment', quantity: 1, unit_price: 8000, discount: 500, amount: 7500 },
      { id: 'itm-2', description: 'Core Buildup Post', quantity: 1, unit_price: 4000, discount: 500, amount: 3500 },
    ],
    payments: [
      { id: 'pmt-1', invoice_id: 'inv-01', amount: 12980, payment_method: 'Card', payment_date: '2025-09-10', received_by_name: 'Emily Watson' },
    ],
  },
  {
    id: 'inv-02',
    patient_id: 'pat-02',
    patient_name: 'Marcus Vance',
    invoice_number: 'INV-2025-002',
    invoice_date: '2025-09-12',
    due_date: '2025-09-22',
    subtotal: 9500,
    discount_amount: 500,
    tax_amount: 1620,
    total_amount: 10620,
    amount_paid: 5000,
    balance: 5620,
    status: 'partial',
    items: [
      { id: 'itm-3', description: 'Professional Laser Teeth Whitening', quantity: 1, unit_price: 9500, discount: 500, amount: 9000 },
    ],
    payments: [
      { id: 'pmt-2', invoice_id: 'inv-02', amount: 5000, payment_method: 'UPI', payment_date: '2025-09-12', received_by_name: 'Emily Watson' },
    ],
  },
];
